# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tide < Formula
  desc "High-speed RSS reader for the terminal"
  homepage "https://github.com/0xfig-labs/tide"
  version "0.7.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/0xfig-labs/tide/releases/download/v0.7.1/tide-darwin-amd64.tar.gz"
      sha256 "a4984adbd4b16407c92fbeed51e25491e81c55718fe0c74986e00cdfc3f1bb1e"

      define_method(:install) do
        bin.install "tide"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/0xfig-labs/tide/releases/download/v0.7.1/tide-darwin-arm64.tar.gz"
      sha256 "8e200691759518ea329c583b9761f1c3528a05a2b65ada444044184add1d6eeb"

      define_method(:install) do
        bin.install "tide"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/0xfig-labs/tide/releases/download/v0.7.1/tide-linux-amd64.tar.gz"
      sha256 "e2c14acb10b4f1bdc60236f1de0912800d92bda0cf8760ebe146791a09050c73"
      define_method(:install) do
        bin.install "tide"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/0xfig-labs/tide/releases/download/v0.7.1/tide-linux-arm64.tar.gz"
      sha256 "c9508bbf4407e435254cef3b5afc7b7b69dcffecf6eaaf8a1fbfddecb32ce425"
      define_method(:install) do
        bin.install "tide"
      end
    end
  end

  test do
    system "#{bin}/tide", "--help"
  end
end
