# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tide < Formula
  desc "High-speed RSS reader for the terminal"
  homepage "https://github.com/0xfig521/tide"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/0xfig521/tide/releases/download/v0.3.0/tide-darwin-amd64.tar.gz"
      sha256 "5ca0e5fc0d1d4affa3d1f9b7ac36c1c6395c1beebd3fc0ae90c7e4e827a5031f"

      define_method(:install) do
        bin.install "tide"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/0xfig521/tide/releases/download/v0.3.0/tide-darwin-arm64.tar.gz"
      sha256 "f3056e034b4732b10bacb696674954a9bbb9460eb9ff2c823ed83cdb416d831e"

      define_method(:install) do
        bin.install "tide"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/0xfig521/tide/releases/download/v0.3.0/tide-linux-amd64.tar.gz"
      sha256 "ef71acde8ce342991ec6ed213a0d6a7a003753bb1d015e11dc82f0b6d9002842"
      define_method(:install) do
        bin.install "tide"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/0xfig521/tide/releases/download/v0.3.0/tide-linux-arm64.tar.gz"
      sha256 "40e268048a525ee69412dc94a7b9e609b447ff3765669b7408192e59c3e447c3"
      define_method(:install) do
        bin.install "tide"
      end
    end
  end

  test do
    system "#{bin}/tide", "--help"
  end
end
