# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tide < Formula
  desc "High-speed RSS reader for the terminal"
  homepage "https://github.com/0xfig521/tide"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/0xfig521/tide/releases/download/v0.5.1/tide-darwin-amd64.tar.gz"
      sha256 "975310e641c1624a9e711e398d0374ee4e5cd03c1adea28e9dc6bde39e88569b"

      define_method(:install) do
        bin.install "tide"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/0xfig521/tide/releases/download/v0.5.1/tide-darwin-arm64.tar.gz"
      sha256 "328f16c145f12c9ab74398f00ead0b2647dd395056a06a1ea2617ef1bbd4a0ea"

      define_method(:install) do
        bin.install "tide"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/0xfig521/tide/releases/download/v0.5.1/tide-linux-amd64.tar.gz"
      sha256 "e4563db3025a96a487236668e71c9304cd90abc6eea82f5430b3f68f4ec93ba3"
      define_method(:install) do
        bin.install "tide"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/0xfig521/tide/releases/download/v0.5.1/tide-linux-arm64.tar.gz"
      sha256 "b3fec14299fe2702c4600e9e75fb38e8ab8f70d3768847c78836cb1b937c41c9"
      define_method(:install) do
        bin.install "tide"
      end
    end
  end

  test do
    system "#{bin}/tide", "--help"
  end
end
